image: python:3.8-buster

stages:
  - test

all_tests:
  stage: test
  script:
    - apt-get update && apt-get install -y build-essential python3-dev libldap2-dev libsasl2-dev
    - pip3 install -r requirements.txt
    - python3 -Wa manage.py test --verbosity=2
