image: python:3.8-buster

stages:
  - test
  - package

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

all_tests:
  stage: test
  before_script:
    - apt-get update && apt-get install -y build-essential libldap2-dev libsasl2-dev
    - pip3 install virtualenv
    - virtualenv -q .venv
    - source .venv/bin/activate
    - pip install -U -r requirements.txt
    - pip install -U -r requirements_dev.txt
  script:
    - make test

bandit:
  stage: test
  before_script:
    - pip3 install virtualenv
    - virtualenv -q .venv
    - source .venv/bin/activate
    - pip install bandit~=1.6.2
  script:
    - make bandit

mypy:
  stage: test
  before_script:
    - apt-get update && apt-get install -y build-essential libldap2-dev libsasl2-dev
    - pip3 install virtualenv
    - virtualenv -q .venv
    - source .venv/bin/activate
    - pip install -U -r requirements.txt
    - pip install -U -r requirements_dev.txt
  script:
    - make mypy
  allow_failure: true

pylint:
  stage: test
  before_script:
    - apt-get update && apt-get install -y build-essential libldap2-dev libsasl2-dev
    - pip3 install virtualenv
    - virtualenv -q .venv
    - source .venv/bin/activate
    - pip install -U -r requirements.txt
    - pip install -U -r requirements_dev.txt
  script:
    - make pylint

package:
  stage: package
  script:
    - make package
  artifacts:
    paths:
    - dist/*.whl
    - dist/*.tar.gz
    expire_in: 1 week