# Generated by Django 3.0.5 on 2020-04-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
