# Generated by Django 3.0.5 on 2020-04-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_election_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='text',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
