# Generated by Django 3.0.5 on 2020-04-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20200430_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='remind_me',
            field=models.BooleanField(default=False),
        ),
    ]
