# Generated by Django 3.0.5 on 2020-04-30 17:38

from django.db import migrations, models
import vote.models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_voter_remind_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=vote.models.avatar_file_name),
        ),
    ]
