# Generated by Django 3.0.5 on 2020-04-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20200423_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='email.email@email', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='election',
            name='application_due_date',
            field=models.DateTimeField(default='2020-04-28 12:00:00'),
            preserve_default=False,
        ),
    ]
