# Generated by Django 3.0.5 on 2020-04-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20200424_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='max_votes_yes',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
