# Generated by Django 3.0.5 on 2020-05-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_auto_20200516_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='election',
            name='meeting_start_time',
        ),
        migrations.AlterField(
            model_name='election',
            name='application_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='voter',
            name='room',
        ),
        migrations.AddField(
            model_name='application',
            name='election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vote.Election'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='voter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='vote.Voter'),
        ),
    ]
