# Generated by Django 3.0.6 on 2020-05-25 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20200524_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='election',
            name='application_due_date',
        ),
        migrations.AddField(
            model_name='application',
            name='room',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='vote.Election'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
