# Generated by Django 3.1.2 on 2020-10-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vote', '0013_auto_20201007_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='voters_self_apply',
            field=models.BooleanField(default=False),
        ),
    ]
