# Generated by Django 3.1.2 on 2020-10-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vote', '0018_auto_20201025_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='remind_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='invite_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
