# Generated by Django 3.2.4 on 2021-06-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0027_auto_20210608_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vote.election'),
        ),
    ]
