# Generated by Django 3.1.14 on 2022-05-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0029_rename_unpublished_and_disable_abstention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='enable_abstention',
            field=models.BooleanField(default=True),
        ),
    ]
