# Generated by Django 3.1.14 on 2022-05-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0030_auto_20220508_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='qr',
            field=models.BooleanField(default=False),
        ),
    ]
