# Generated by Django 3.0.5 on 2020-04-22 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20200422_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='vote.User'),
        ),
    ]
