# Generated by Django 3.0.5 on 2020-04-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20200423_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[('accept', 'für'), ('abstention', 'Enthaltung'), ('reject', 'gegen')], max_length=10),
        ),
    ]
